#!/bin/bash
### newprog
clear;
echo "delete a language with all memos";
echo "-------------/!\ irreversible----------";
echo "languages list :";
ls -m db/ ;
### setup
bool=0;

### start
echo "language to delete :";
read nom;
echo "Do you want to delete this memo ? (y/n)";
echo -n "}>"; read answer;
if [ $answer = "y" ] ; then
	rm -r db/`echo $nom` ;
	echo $nom" est supprime.";
fi